import Head from 'next/head';
import { ReportLanguageSelector } from '../app/core/components/ReportLanguageSelector';
import { SiteLanguageSelector } from '../app/core/components/SiteLanguageSelector';
import { serverSideReportTranslations } from '../app/core/utils/serverSideReportTranslations';
import { serverSideSiteTranslations } from '../app/core/utils/serverSideSiteTranslations';
import { Feature1 } from '../app/features/feature1/components/Feature1';
import { Feature2 } from '../app/features/feature2/components/Feature2';

export default function Home() {
  return (
    <div style={{ padding: 20 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SiteLanguageSelector />
      <Feature1 />

      <ReportLanguageSelector />
      <Feature2 />
    </div>
  );
}

export const getServerSideProps = async ({ locale, locales }) => ({
  props: {
    ...(await serverSideSiteTranslations(locale, locales, ['feature1', 'feature2'])),
    ...(await serverSideReportTranslations(locale, locales, ['feature1', 'feature2'])),
  },
});
